### ISSUE TITLE
It has not been possible to download the required files

### ISSUE THREAD

**Issue by jerronl** [timeseriesAI/tsai#818] opened 2023-08-11 03:03 UTC
When I ran in Colab
```
X_, y_, splits_ = get_UCR_data('LSST', split_data=False)
type(X_), type(y_), type(splits_)

```
I got follwing error:

```

It has not been possible to download the required files

(NoneType, NoneType, NoneType)
```

the output of my_setup:
```
os              : Linux-5.15.109+-x86_64-with-glibc2.35
python          : 3.10.12
tsai            : 0.3.7
fastai          : 2.7.12
fastcore        : 1.5.29
sklearn         : 1.2.2
torch           : 2.0.1+cu118
device          : 1 gpu (['Tesla T4'])
cpu cores       : 1
threads per cpu : 2
RAM             : 12.68 GB
GPU memory      : [15.0] GB
```

**Comment by whao159107** [comment] 2023-08-13 10:07
The download link for
 "http://www.timeseriesclassification.com/ClassificationDownloads/StarLightCurves.zip" 
is not working.
thank you！！

**Comment by Huzaifa-crypton** [comment] 2023-08-29 18:05
Facing the same issue as mentioned by @jerronl. What is the other way around this?

**Comment by fomightez** [comment] 2023-09-02 21:18
Doesn't [here](https://github.com/timeseriesAI/tsai/issues/765#issuecomment-1652860405) already cover this issue, and importantly, describe a way to address it?

**Comment by oguiza** [comment] 2023-09-03 11:12
Duplicate of #765 which is now fixed.

**Closed by oguiza** 2023-09-03 11:12 UTC
