### ISSUE TITLE
Error importing tsai.all

### ISSUE THREAD

**Issue by Lidors** [timeseriesAI/tsai#142] opened 2021-06-29 09:05 UTC
Hi, 

I am traying to import the tsai library using the following command: from tsai.all import *
However, I get the following error: 

" LinkerError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.2; current version is '7.0'
ptxas fatal   : Ptx assembly aborted due to errors"

I am using a CUDA version of 11.2 

any idea on how to solve it?

Thanks

**Comment by oguiza** [comment] 2021-06-30 11:24
Hi @Lidors, 
I've never seen that issue before. And I'm not too familiar with cuda to be honest with you. It's strange though. When I install `tsai`in Google Colba it works fine.  And when I use:
```
!nvidia-smi
```
 it shows CUDA Version: 11.2.
I'm sorry I can't help. I don't know if others will be able to help you.

**Comment by TKassis** [comment] 2021-07-08 14:56
@Lidors CUDA problems might be out of the scope of this repo. There could be many possibilities why you are having issues. I would Google around! Start by making sure you have an NVIDIA card and up-to-date drivers installed. the easiest way to set stuff up is using Anaconda. Install Pytorch using the instructions on their website for Conda then install TSAI.

**Comment by oguiza** [comment] 2021-07-15 07:19
I will close this issue as I've been unable to reproduce it. Please, reopen if required.

**Closed by oguiza** 2021-07-15 07:19 UTC
