### ISSUE TITLE
TSTPlus with MVP throws error when provided max_seq_len arg

### ISSUE THREAD

**Issue by dnth** [timeseriesAI/tsai#173] opened 2021-08-13 06:53 UTC
When I try to instantiate a learner with `TSTPlus` and `MVP` callback and provided a `max_seq_len` that is shorter than the sequence length, it throws an error with input shape. Is this expected? Here is a [link](https://colab.research.google.com/drive/1nm4p-bqBnjBAjYuSJIljp1n9wpBtskE8?usp=sharing) to a colab notebook for more details.

```
learn = ts_learner(udls100, TSTPlus, max_seq_len=10,
                   cbs=[ShowGraph(), MVP(target_dir='./data/MVP', fname=f'{dsid}_200')])
```

``` python
AssertionError                            Traceback (most recent call last)
<ipython-input-144-d81c6bd29d71> in <module>()
----> 1 learn.lr_find()

9 frames
/usr/local/lib/python3.7/dist-packages/tsai/callback/MVP.py in before_fit(self)
    172         with torch.no_grad():
    173             xb = torch.randn(2, self.learn.dls.vars, self.learn.dls.len).to(self.learn.dls.device)
--> 174             assert xb.shape == self.learn.model(xb).shape, 'the model cannot reproduce the input shape'
    175 
    176     def before_batch(self):

AssertionError: the model cannot reproduce the input shape
```

```
tsai       : 0.2.19
fastai     : 2.5.1
fastcore   : 1.3.26
torch      : 1.9.0+cu102
```

**Comment by oguiza** [comment] 2021-08-28 18:14
Hi @dnth,
The issue here is that MVP is a callback that masks part of the data, and forces the model to reproduce the input (somewhat similar to what autoencoders do). But in your case, you make the model change the length of the sequence. You get the error because the model is unable to reproduce the input shape (the data coming from the dataloader). Have you tried it without modifying max_seq_len?

**Comment by dnth** [comment] 2021-08-31 02:47
I see.. thank you for the explanation. If I do not modify the max_seq_len everything works as usual. However, I want the model to only consider a shorter sequence length. Is there a better way to do it?

**Comment by oguiza** [comment] 2021-09-09 17:43
I believe you can pass a custom_head to MVP that shortens the seq_len to the max_seq_len. I've never tried that but it might work.

**Comment by oguiza** [comment] 2021-11-18 08:45
I'll close this issue due to a lack of a response. Please, reopen it if necessary.

**Closed by oguiza** 2021-11-18 08:45 UTC
Labels: question
