### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update' running tutorial 04_Intro_to_Time_Series_Regression

### ISSUE THREAD

**Issue by Johnreidsilver** [timeseriesAI/tsai#116] opened 2021-05-16 20:24 UTC
Hi, first of all thank you for the great program and also for integrating rocket !

While running the tutorial:
[04_Intro_to_Time_Series_Regression ](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/04_Intro_to_Time_Series_Regression.ipynb)

when trying to fit the model:
`learn.fit_one_cycle(50, 1e-2)`
Throws an error:
`AttributeError: 'NoneType' object has no attribute 'update'`

earlier I ran into a dimension mismatch, but it was due to not loading the splits in get_ts_dls

Up to this point the only thing that didn't go as the tutorial was that while check_data(X, y,splits) displayed the bar
dls.show_batch() didn't display any graphs (needs `plot.show()` ) and 
dls.one_batch()
(TSTensor(samples:95, vars:24, len:144), tensor([18.5600, 10.8000, 22.1000, 18.1800, 14.0600, 17.6600,  8.6200, 11.2300,
didn't show the exact same numbers as the tutorial:
(TSTensor(samples:95, vars:24, len:144),
 tensor([10.8000, 10.5100, 13.5600, 21.6900, 16.5300, 16.2500, 11.0600, 11.6400,

My versions:

>>>print('tsai     :', tsai.__version__)
tsai     : 0.2.17
>>> print('fastai     :', fastai.__version__)
fastai     : 2.3.1
>>> print('fastcore   :', fastcore.__version__)
fastcore   : 1.3.20
>>> print('torch      :', torch.__version__)
torch      : 1.8.1+cu102

Python 3.8.5
Ubuntu 20.04.1 LTS

**Comment by oguiza** [comment] 2021-05-29 11:19
I've rerun the notebook, but couldn't reproduce your issue. 
I've noticed though that occasionally, data load (which happens with an URL) may fail for some reason. But in this case, no data will be loaded. I'm not sure this is your case.

**Comment by oguiza** [comment] 2021-06-10 09:04
I will close this issue due to a lack of response. Please, reopen if needed.

**Comment by mtorabirad** [comment] 2021-07-13 13:51
@oguiza @vrodriguezf @williamsdoug 

First of all, thank you for making this code available. 

I also have the same issue. Any comments would be appreciated.

**Comment by oguiza** [comment] 2021-07-14 18:58
Hi @mtorabirad,
Thanks for your comments.
Could you please provide some more details on where does the issue appear? Have you upgraded `tsai` to the most recent version? Does the issue always occur, or just sporadically?

**Comment by oguiza** [comment] 2021-07-14 18:59
Reopen issue. Waiting for clarification.

**Comment by mtorabirad** [comment] 2021-07-16 14:39
Thank you @oguiza for the reply. 

My version information is as follows

tsai       : 0.2.18 (this is the latest version right?)
fastai     : 2.4
fastcore   : 1.3.20
torch      : 1.9.0+cu102

The error occurs in line "learn.fit_one_cycle(50, 1e-2)".

By further debugging the code, I noticed that the error is coming from line "self.graph_out.update(self.graph_ax.figure)" of method "update_graph" within class "ShowGraph" defined in file "callback/core.py."

**Comment by oguiza** [comment] 2021-07-16 18:38
I've investigated this but based on your description I have no idea what the issue is. 
I've re-run the notebook in Google Colab using `tsai==0.2.18` (which is the latest pip version) and `tsai==0..2.19` which is the most recent version in GitHub and the notebook runs perfectly. You can see them in [gist 0.2.18](https://colab.research.google.com/gist/oguiza/ccb230e19cb5c88b97b7b93ca82831e3/04_intro_to_time_series_regression.ipynb) and [gist 0.2.19](https://colab.research.google.com/gist/oguiza/e1a7d632ec36e62fc5e92f0fea5a5cea/04_intro_to_time_series_regression.ipynb).
Have you made any changes to the notebook?
Is the output of all cells the same as in the tutorial nb except the cell where you find the issue?
Can you post the full trace?

**Comment by mtorabirad** [comment] 2021-07-21 17:40
Thank you @oguiza for your reply. 

Actually, I noticed that I get this error only when running the contents of the notebook in a Python script. When I run the notebook it self (i.e., ipyn file) I do not get any errors. 

The full trace of the error is below. The ".py" file I am running things from is "test_tsai.py" (you can search the name in the trace below)
------------------------------------------------------------------------------------------------------------------------------
'NoneType' object has no attribute 'update'
 File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/tsai/callback/core.py", line 106, in update_graph
    self.graph_out.update(self.graph_ax.figure)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/tsai/callback/core.py", line 88, in after_epoch
    self.update_graph([(iters, rec.losses), (self.nb_batches, val_losses)], x_bounds, y_bounds)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/callback/core.py", line 45, in __call__
    if self.run and _run: res = getattr(self, event_name, noop)()
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastcore/basics.py", line 651, in __call__
    return self.func(*fargs, **kwargs)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastcore/basics.py", line 666, in map_ex
    return list(res)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastcore/foundation.py", line 154, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/learner.py", line 165, in _with_events
    self(f'after_{event_type}');  final()
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/learner.py", line 212, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/learner.py", line 163, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/site-packages/fastai/callback/schedule.py", line 113, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/mahdi/Desktop/..._files/.../test_tsai.py", line 40, in <module>
    learn.fit_one_cycle(50, 1e-2)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mahdi/anaconda3/envs/.../lib/python3.8/runpy.py", line 192, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,

------------------------------------------------------------------------------------------------------------------------------

Do you have any comments on why I may be getting this issue when running the contents in a .py file?

**Comment by oguiza** [comment] 2021-07-26 17:12
Hi @mtorabirad,

The issue you report seems to be due to the use of the ShowGraph callback. When running a script, there's no printed graph. So it tries to updated it, it cannot find it. Please, try it again removing the callback. 
I've tried the following code in a script: 
```
from tsai.all import *

dsid = 'AppliancesEnergy' 
PATH = Path('./models/Regression.pkl')

X, y, splits = get_regression_data(dsid, split_data=False)
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=128)
learn = ts_learner(dls, InceptionTime, metrics=[mae, rmse])
learn.fit_one_cycle(50, 1e-2)

PATH.parent.mkdir(parents=True, exist_ok=True)
learn.export(PATH)
learn = load_learner(PATH, cpu=False)
_, _, preds = learn.get_X_preds(X[splits[1]])
np.save('test.npy', preds)
print('predictions saved, preds.shape')
```
 and it works well.

**Comment by mtorabirad** [comment] 2021-07-26 17:52
@oguiza I tried your solution and it works. Thank you!

**Comment by oguiza** [comment] 2021-07-26 17:59
@mtorabirad, I'm glad to hear that!
Based on your feedback, I'll close this issue.

**Closed by oguiza** 2021-07-26 17:59 UTC
Labels: good first issue
