### ISSUE TITLE
[Question] Labels in TSUnwindowedDataset

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [timeseriesAI/tsai#235] opened 2021-10-10 07:59 UTC
Hi, this is a question about the unwindoweddataset. I am just wondering if someone could help me with that.

Assume that I have the code below:

window_size = 2

```
X = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
]
X = numpy.asarray(X)

Y = [1, 2, 3, 4, 5]
Y = numpy.asarray(Y)

ds = TSUnwindowedDataset(X, y=Y, window_size=window_size, stride=1)
```
I am just wondering how to make sure that the labels (y) are the same as SlidingWindow() with horizon = 0 with [None, [Categorize()]] applied in datasets?

 If I print the type of an item out like this:
```
 it = iter(ds)
print(next(it))
```
I get (TSTensor(samples:1, vars:3, len:2, device=cpu), TSLabelTensor(shape:(1, 2)))
While I am expecting the label to be binary - either 0 or 1.

**Comment by oguiza** [comment] 2021-10-10 08:55
Hi @TheLonelinessOfHS,
I'm sorry but I don't understand your question. How could the label be binary (0,1) if the input is [1,2,3,4,5]? Could you please clarify your question?

**Comment by oguiza** [comment] 2021-10-10 09:28
The example you provided shows how TSUnwindowedDataset was designed to work.  If you set the window size to 2, the y output should have a shape of (batch size, 2). I still don't understand what you'd expect to get.

**Comment by oguiza** [comment] 2021-11-15 12:43
Hi @TheLonelinessOfHS, 
There's an attribute in TSUnwindowedDataset that is y_func. You can pass any function to calculate y based on all y's in the defined window. 
From your example, I don't understand where y1=1 and y2=1 come from.
I'm not sure if y_func could help.

**Comment by oguiza** [comment] 2021-11-25 08:45
I'll close this issue due to a lack of a response. Please, reopen it if necessary.

**Closed by oguiza** 2021-11-25 08:45 UTC
Labels: question
