### ISSUE TITLE
UCR Dataset download link

### ISSUE THREAD

**Issue by irosyadi** [timeseriesAI/tsai#827] opened 2023-09-02 00:29 UTC
The UCR dataset download link should be changed from http://www.timeseriesclassification.com/ClassificationDownloads to http://www.timeseriesclassification.com/aeon-toolkit

**Comment by oguiza** [comment] 2023-09-03 11:11
Thanks for providing a solution @irosyadi!
Duplicate of #765 which is now fixed.

**Closed by oguiza** 2023-09-03 11:11 UTC

**Comment by lelouch514** [comment] 2023-09-15 05:56
I switched to the new link but still report error? Is there a new update?
