### ISSUE TITLE
0.2.14 error

### ISSUE THREAD

**Issue by shushan2017** [timeseriesAI/tsai#50] opened 2021-01-19 10:07 UTC
The code that works on version 0.2.11 goes wrong on Version 2.14, and nothing has changed about the code

X, y, splits = combine_ split_ data([X_ train, X_ test], [y_ train, y_ test])

tfms = [None, [Categorize()]]

batch_ tfms=TSStandardize(by_ var=True)

dls = get_ ts_ dls(X, y, tfms=tfms, splits=splits, bs=64, batch_ tfms=batch_ tfms)

learn = ts_ learner(dls, TST, loss_ func=LabelSmoothingCrossEntropyFlat(), res_ dropout=0.3, fc_ dropout=0.9, metrics=[RocAucBinary(), accuracy], cbs=ShowGraph())

start = time.time ()

learn.load ('md1')

********************

probas, targets, preds = learn.get_ X_ preds(X, with_ decoded=True)

# error

***************

  File "f:\Anaconda3\lib\site-packages\tsai\learner.py", line 216, in get_X_preds
    return self.get_preds(dl=self.dls.new_dl(X, y=y), **kwargs)

  File "f:\Anaconda3\lib\site-packages\fastai\learner.py", line 250, in get_preds
    if reorder and hasattr(dl, 'get_idxs'): res = nested_reorder(res, tensor(idxs).argsort())

  File "f:\Anaconda3\lib\site-packages\fastai\torch_core.py", line 697, in nested_reorder
    elif is_listy(t): return type(t)(nested_reorder(t_, idxs) for t_ in t)

  File "f:\Anaconda3\lib\site-packages\fastai\torch_core.py", line 697, in <genexpr>
    elif is_listy(t): return type(t)(nested_reorder(t_, idxs) for t_ in t)

  File "f:\Anaconda3\lib\site-packages\fastai\torch_core.py", line 696, in nested_reorder
    if isinstance(t, (Tensor,L)): return t[idxs]

IndexError: index 124 is out of bounds for dimension 0 with size 124

**Comment by oguiza** [comment] 2021-01-20 20:36
Hi @shushan2017, 
Thanks a lot for raising this issue. This has helped me address something important I hadn't previously noticed.
I believe the issue is fixed now. I've tested it with this code which was failing before (with the same error you reported) and is now working well: 

```
from tsai.all import *

X, y, splits = get_UCR_data('Heartbeat', split_data=False)
tfms = [None, [Categorize()]]
batch_tfms=TSStandardize(by_var=True)
dls = get_ts_dls(X, y, tfms=tfms, splits=splits, bs=64, batch_tfms=batch_tfms)
learn = ts_learner(dls, TST, loss_func=LabelSmoothingCrossEntropyFlat(), res_dropout=0.3, fc_dropout=0.9, 
                   metrics=[RocAucBinary(), accuracy], cbs=ShowGraph())
probas, targets, preds = learn.get_X_preds(X[splits[1]], with_decoded=True)
```
Please, try it and let me know if it works well. 
I've fixed this bug in github. I will make a new pip release soon.

**Comment by oguiza** [comment] 2021-01-22 17:10
I'm glad to hear that!. 
I'll close the issue then. Please, reopen it in case it repeats. Thanks!

**Closed by oguiza** 2021-01-22 17:10 UTC
Labels: good first issue
