### ISSUE TITLE
Different length of predicted vs target class labels

### ISSUE THREAD

**Issue by sarwanpasha** [timeseriesAI/tsai#433] opened 2022-03-18 20:15 UTC
I have a time series data and I am using InceptionTime model for classification. However, when I try to predict the labels on unseen test set, the number of predicted labels are more that the data objects (rows) in the original test set. When I use 1 epoch, I get the same length for predicted and target class. But when I use >1 epochs, the number of predicted labels are more than the target labels
Here is the code I am using for prediction of labels. 

`test_probas2, test_targets2, test_preds2 = learn.get_X_preds(X_test, y_test, with_decoded=True)`

**Comment by oguiza** [comment] 2022-03-19 19:12
Hi @sarwanpasha , I'm afraid I won't be able to help unless you submit a code snippet to reproduce the issue.

**Comment by sarwanpasha** [comment] 2022-03-19 19:27
Here is my code for training the inceptionTime model



```
tfms = [None, Categorize()]
batch_tfms = [TSStandardize()]
splits_new = get_splits(np.array(y), valid_size=.10, test_size=.10, random_state=23, stratify=True)
dsets = TSDatasets(X, y, tfms=tfms, splits=splits_new)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=32, batch_tfms=batch_tfms)
dls.show_batch()
epochs = 6
model = create_model(InceptionTime, dls=dls)
learn = Learner(dls, model, metrics=accuracy)
start = time.time()
learn.fit_one_cycle(epochs, lr_max=1e-3)
print(f"\ntraining time: {time.strftime('%H:%M:%S', time.gmtime(time.time() - start))}")
learn.plot_metrics()
```

Now, when I try to predict the test set labels using the trained model, I use the following code

`test_probas2, test_targets2, test_preds2 = learn.get_X_preds(X_test, with_decoded=True)`

But when I increase the number of epochs, the number of target labels in variable "test_targets2" and different from predicted values variable in "test_preds2".

For 1 epoch, the length of target and predicted label is same, but with increasing epochs, the number of predicted labels increases than the original labels in the test set.

**Comment by oguiza** [comment] 2022-03-19 19:52
And what are X and y shapes? I'm trying to reproduce the issue.

**Comment by sarwanpasha** [comment] 2022-03-19 19:55
X shape is (7000, 1, 1274)
y shape is (7000,)

**Comment by sarwanpasha** [comment] 2022-03-19 19:57
Then I split the data into train and test set using "get_splits" function. For the train data, I then use train and validation splits while keep the test set separate for prediction on unseen data

**Comment by oguiza** [comment] 2022-03-19 20:09
I've tried to reproduce the issue but I can't. Please, try the following code: 
```python
X = np.random.rand(7000, 1, 1274)
y = np.random.randint(0, 3, (7000,))

tfms = [None, TSCategorize()]
batch_tfms = [TSStandardize()]
splits_new = get_splits(np.array(y), valid_size=.10, test_size=.10, random_state=23, stratify=True)
dsets = TSDatasets(X, y, tfms=tfms, splits=splits_new)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=32, batch_tfms=batch_tfms)
dls.show_batch()
epochs = 1
model = create_model(InceptionTime, dls=dls)
learn = Learner(dls, model, metrics=accuracy)
start = time.time()
learn.fit_one_cycle(epochs, lr_max=1e-3)
print(f"\ntraining time: {time.strftime('%H:%M:%S', time.gmtime(time.time() - start))}")
learn.plot_metrics()
test_probas2, test_targets2, test_preds2 = learn.get_X_preds(X[splits_new[2]], with_decoded=True)
test_probas2, test_targets2, test_preds2
```

**Comment by sarwanpasha** [comment] 2022-03-20 20:32
I used your code but I still get that error. Basically the test set has 700 samples while the predicted values are 928. This happened when I used 6 epochs. With different value of epochs, I get varying number of predicted samples. Here is the error:
"ValueError: Found input variables with inconsistent numbers of samples: [700, 928]"

**Comment by oguiza** [comment] 2022-03-21 08:32
I'm sorry @sarwanpasha , but I can't reproduce the issue. 
I've tried this code:
```python
X = np.random.rand(7000, 1, 1274)
y = np.random.randint(0, 3, (7000,))

tfms = [None, TSCategorize()]
batch_tfms = [TSStandardize()]
splits_new = get_splits(np.array(y), valid_size=.10, test_size=.10, random_state=23, stratify=True)
dsets = TSDatasets(X, y, tfms=tfms, splits=splits_new)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=32, batch_tfms=batch_tfms)
dls.show_batch()
epochs = 6
model = create_model(InceptionTime, dls=dls)
learn = Learner(dls, model, metrics=accuracy)
start = time.time()
learn.fit_one_cycle(epochs, lr_max=1e-3)
print(f"\ntraining time: {time.strftime('%H:%M:%S', time.gmtime(time.time() - start))}")
learn.plot_metrics()
test_probas2, test_targets2, test_preds2 = learn.get_X_preds(X[splits_new[2]], with_decoded=True)
test_probas2.shape, test_preds2.shape
```
and the output I get is (torch.Size([700, 3]), (700,)) which is the expected one. 
Could you please run 
```python
my_setup()
```
and post your results. 
I used Colab and this is what I got: 
```bash
os             : Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
python         : 3.7.12
tsai           : 0.3.1
fastai         : 2.5.3
fastcore       : 1.3.29
torch          : 1.10.0+cu111
device         : 1 cuda (['Tesla P100-PCIE-16GB'])
n_cpus         : 2
RAM            : 12.69 GB
GPU memory     : [15.9] GB
```

**Comment by oguiza** [comment] 2022-04-14 05:48
I’ll close this issue due to a lack of a response. Please, reopen if necessary.

**Closed by oguiza** 2022-04-14 05:48 UTC
Labels: under review
