### ISSUE TITLE
AttributeError: Exception occured in `ShowGraph` when calling event `after_epoch`: 	'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by sunmingliu** [timeseriesAI/tsai#518] opened 2022-05-22 03:34 UTC
from tsai.all import *
my_setup()
regression_list
dsid = 'AppliancesEnergy'
X, y, splits = get_regression_data(dsid, split_data=False)
X.shape, y.shape, y[:10]
check_data(X, y, splits)
tfms = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=128)
dls.one_batch()
dls.c
dls.show_batch()
learn = ts_learner(dls, InceptionTime, metrics=[mae, rmse], cbs=ShowGraph())
learn.lr_find()
learn.loss_func
learn = ts_learner(dls, InceptionTime,  metrics=[mae, rmse], cbs=ShowGraph())
learn.fit_one_cycle(50, 1e-2)
--------------------------------------------------------------------------------------
epoch     train_loss  valid_loss  mae       _rmse     time    
0         212.116226  199.891907  13.711620 14.138313 00:00     
Figure(600x400)
Traceback (most recent call last):
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 132, in added_cbs
    try: yield
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 222, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 164, in _with_events
    try: self(f'before_{event_type}');  f()
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 213, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 166, in _with_events
    self(f'after_{event_type}');  final()
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 142, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastcore\foundation.py", line 155, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastcore\basics.py", line 780, in map_ex
    return list(res)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastcore\basics.py", line 765, in __call__
    return self.func(*fargs, **kwargs)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\learner.py", line 146, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\fastai\callback\core.py", line 57, in __call__
    try: res = getattr(self, event_name, noop)()
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\tsai-0.3.1-py3.8.egg\tsai\callback\core.py", line 94, in after_epoch
    self.update_graph([(iters, rec.losses), (self.nb_batches, val_losses)], x_bounds, y_bounds)
  File "C:\softwares\study\Anaconda\path\envs\tsai_0.3.1\lib\site-packages\tsai-0.3.1-py3.8.egg\tsai\callback\core.py", line 113, in update_graph
    self.graph_out.update(self.graph_ax.figure)
AttributeError: Exception occured in `ShowGraph` when calling event `after_epoch`:
	'NoneType' object has no attribute 'update'
python-BaseException

**Comment by oguiza** [comment] 2022-05-22 07:37
Hi @sunmingliu,
I tried to reproduce your issue but the code works well (see [gist](https://colab.research.google.com/gist/oguiza/9b95473267295bd2242d9682e836ffd3/scratchpad.ipynb)).
You may need to upgrade tsai to the most recent version.

**Comment by sunmingliu** [comment] 2022-05-22 09:52
Hi, @oguiza ,
I installed tsai-0.3.1 with python==3.8. Could you please tell me your tsai and python version?

**Comment by oguiza** [comment] 2022-05-22 11:19
I usually use this:
```python
# **************** UNCOMMENT AND RUN THIS CELL IF YOU NEED TO INSTALL/ UPGRADE TSAI ****************
stable = False # Set to True for latest pip version or False for main branch in GitHub
!pip install {"tsai -U" if stable else "git+https://github.com/timeseriesAI/tsai.git"} >> /dev/null
```
I run it in colab. These is the setup (you can just run ```my_setup()``` to get yours):
```bash
os             : Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
python         : 3.7.13
tsai           : 0.3.2
fastai         : 2.6.3
fastcore       : 1.4.3
torch          : 1.11.0+cu113
device         : 1 gpu (['Tesla P100-PCIE-16GB'])
cpu cores      : 2
RAM            : 12.68 GB
GPU memory     : [15.9] GB
```

**Comment by sunmingliu** [comment] 2022-05-22 12:05
I have tried  different tsai versions on windows+pycharm. This error always appeared.
os : Windows-10-10.0.19041-SP0
python : 3.8.0
tsai : 0.3.2
fastai : 2.5.6
fastcore : 1.4.3
torch : 1.11.0+cpu
device : cpu
cpu cores : 20
RAM : 31.75 GB
GPU memory : [6.0] GB

**Comment by sunmingliu** [comment] 2022-06-13 09:32
> I encountered the same problem, tried various versions of the library, but it didn't work
try: learn = ts_learner(dls, GRU, metrics=[mae, rmse], cbs=ShowGraph())
I finally removed ShowGraph, which led to not updating the graph after each epoch (the bug occured in ShowGraph when calling event after_epoch)

**Comment by huameichen0523** [comment] 2022-06-21 19:54
sunmingliu's solution works for me.

> I have tried different tsai versions on windows+pycharm. This error always appeared. I think something is wrong with IPython because it is always interrupted where self.graph_out.update(self.graph_ax.figure). I commented these codes and it ran well. os : Windows-10-10.0.19041-SP0 python : 3.8.0 tsai : 0.3.2 fastai : 2.5.6 fastcore : 1.4.3 torch : 1.11.0+cpu device : cpu cpu cores : 20 RAM : 31.75 GB GPU memory : [6.0] GB

**Comment by oguiza** [comment] 2022-08-18 10:02
Could anybody please confirm if this is still an open issue? Otherwise, I'll close it.

**Comment by parshinsh** [comment] 2022-08-24 16:45
> Could anybody please confirm if this is still an open issue? Otherwise, I'll close it.

It's still an open issue! I'm facing the same error although using the library versions suggested above on Linux.

**Comment by hairtail-cheng** [comment] 2022-08-28 16:05
I also encountered the same problem mentioned in the issue. The solution proposed by @sunmingliu  also works in my case.

The commented code location: callback\core.py line113

os             : Windows-10-10.0.19041-SP0
python         : 3.8.5
tsai           : 0.3.1
fastai         : 2.7.9
fastcore       : 1.5.22
torch          : 1.8.1+cu111
device         : 1 gpu (['GeForce MX250'])
cpu cores      : 8
RAM            : 11.82 GB
GPU memory     : [2.0] GB

**Comment by GEMyy129** [comment] 2022-09-28 03:10
I also encountered the same problem mentioned in the issue. The solution proposed by @sunmingliu also works in my case. However, how can I view the figure after commenting the code?

**Comment by oguiza** [comment] 2022-12-07 09:54
Hi @hairtail-cheng , @sunmingliu , @huameichen0523 ,
When you say that commenting out line 113 (115 in the GitHub version 0.3.5) in callback\core.py works for you, do you mean the chart is still updated correctly? I've tried commenting out that line and the code runs, but I get no chart as expected. 

There seems to be an open issue in fastai that might be related to this one: https://github.com/fastai/fastai/issues/3814

**Comment by oguiza** [comment] 2022-12-07 15:44
Thanks @huameichen0523 for your quick reply. 
My question is if the code when you modify the code adding an if statement: 
```python
if self.graph_out is not None:
            self.graph_out.update(self.graph_ax.figure)
```
does it still produce a chart that is updated with every epoch?

**Comment by oguiza** [comment] 2023-01-19 13:38
Closed due to lack of response.

**Closed by oguiza** 2023-01-19 13:38 UTC
Labels: under review
