### ISSUE TITLE
Incorrect conversion create_scripts(nb_name) in 'nbs'

### ISSUE THREAD

**Issue by forhonourlx** [timeseriesAI/tsai#448] opened 2022-03-27 13:39 UTC
Hi tsai Team,

Trying:
```
from tsai.imports import *
from tsai.export import *
nb_name = get_nb_name()
# nb_name = "121_models.TabTransformer.ipynb"
create_scripts(nb_name);
```
got:
```
Output exceeds the [size limit](command:workbench.action.openSettings?["notebook.output.textLineLimit"]). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?5c9b3a90-e3cf-4d30-9886-28f2a4400f35)
Converted 000_export.ipynb.
Converted 001_utils.ipynb.
Converted 010_data.validation.ipynb.
Converted 011_data.preparation.ipynb.
Converted 012_data.external.ipynb.
Converted 013_data.core.ipynb.
Converted 014_data.unwindowed.ipynb.
Converted 015_data.metadatasets.ipynb.
Converted 016_data.preprocessing.ipynb.
Converted 017_data.transforms.ipynb.
Converted 018_data.mixed_augmentation.ipynb.
Converted 019_data.image.ipynb.
Converted 020_data.features.ipynb.
Converted 021_data.tabular.ipynb.
Converted 022_data.mixed.ipynb.
Converted 050_losses.ipynb.
Converted 051_metrics.ipynb.
Converted 052_learner.ipynb.
Converted 052a_inference.ipynb.
Converted 052b_analysis.ipynb.
Converted 052c_calibration.ipynb.
Converted 052d_tslearner.ipynb.
Converted 053_optimizer.ipynb.
Converted 060_callback.core.ipynb.
Converted 060_callback.experimental.ipynb.
...
c:\Users\simon\Desktop\Invest\DL\tsai_220323\tsai\models\__init__.py saved     417049 s ago ***
Incorrect conversion! 😔
Total time elapsed 4170555.728 s
```

How can I solve this? Thanks.

**Comment by oguiza** [comment] 2022-03-27 17:15
Hi @forhonourlx,
It seems the issue is that the code in the notebook creates a very long output. Is there any way you can shorten that output and try it again?

**Comment by oguiza** [comment] 2022-04-14 05:46
I’ll close the issue due to a lack of a response. Please, reopen if necessary.

**Closed by oguiza** 2022-04-14 05:46 UTC
Labels: question
