### ISSUE TITLE
Failing tutorial notebook 06_TS_to_image_classification

### ISSUE THREAD

**Issue by williamsdoug** [timeseriesAI/tsai#62] opened 2021-02-18 23:30 UTC
Notebook tutorial_nbs/06_TS_to_image_classification fails in cell  32 on both my local system and reproduces on Google Colab.  With the exception of call 32, all other cells function properly including cells 33+

**Local system configuration:**
tsai       : 0.2.16
fastai     : 2.2.5
fastcore   : 1.3.19
torch      : 1.7.0
sklearn    : 0.24.1
torch      : 0.11.0
numba      : 0.52.0
sys.version: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

**Google Colab Configuration:**
/usr/local/lib/python3.6/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)
tsai       : 0.2.16
fastai     : 2.2.5
fastcore   : 1.3.19
torch      : 1.7.0+cu101
sklearn   : 0.22.2.post1
torch      : 0.11.0
numba      : 0.52.0
sys.version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]

----------------------------------------------------------------
Cell 32:
model = create_model(xresnet34, dls=dls)
learn = Learner(dls, model, metrics=accuracy)
start = time.time()
learn.fit_one_cycle(epochs, lr_max=1e-3)
print(f"\ntraining time: {time.strftime('%H:%M:%S', time.gmtime(time.time() - start))}")
learn.plot_metrics()
--------------------------------------------------------------------
Error Message:

Note:  Error occurs during training at 50.00% [1/2 00:01<00:01] 

/home/doug/anaconda3/envs/tsai2/lib/python3.8/site-packages/pyts/preprocessing/discretizer.py:159: UserWarning: Some quantiles are equal. The number of bins will be smaller for sample [891]. Consider decreasing the number of bins or removing these samples.
  warn("Some quantiles are equal. The number of bins will be "
/home/doug/anaconda3/envs/tsai2/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

---------------------------------------------------------------------------
UnsupportedError                          Traceback (most recent call last)
<ipython-input-32-95a60c8a84d5> in <module>
      2 learn = Learner(dls, model, metrics=accuracy)
      3 start = time.time()
----> 4 learn.fit_one_cycle(epochs, lr_max=1e-3)
      5 print(f"\ntraining time: {time.strftime('%H:%M:%S', time.gmtime(time.time() - start))}")
      6 learn.plot_metrics()

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/callback/schedule.py in fit_one_cycle(self, n_epoch, lr_max, div, div_final, pct_start, wd, moms, cbs, reset_opt)
    110     scheds = {'lr': combined_cos(pct_start, lr_max/div, lr_max, lr_max/div_final),
    111               'mom': combined_cos(pct_start, *(self.moms if moms is None else moms))}
--> 112     self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
    113 
    114 # Cell

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    209             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    210             self.n_epoch = n_epoch
--> 211             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    212 
    213     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in _do_fit(self)
    200         for epoch in range(self.n_epoch):
    201             self.epoch=epoch
--> 202             self._with_events(self._do_epoch, 'epoch', CancelEpochException)
    203 
    204     def fit(self, n_epoch, lr=None, wd=None, cbs=None, reset_opt=False):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in _do_epoch(self)
    195     def _do_epoch(self):
    196         self._do_epoch_train()
--> 197         self._do_epoch_validate()
    198 
    199     def _do_fit(self):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in _do_epoch_validate(self, ds_idx, dl)
    191         if dl is None: dl = self.dls[ds_idx]
    192         self.dl = dl
--> 193         with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)
    194 
    195     def _do_epoch(self):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    158 
    159     def _with_events(self, f, event_type, ex, final=noop):
--> 160         try: self(f'before_{event_type}');  f()
    161         except ex: self(f'after_cancel_{event_type}')
    162         self(f'after_{event_type}');  final()

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/learner.py in all_batches(self)
    164     def all_batches(self):
    165         self.n_iter = len(self.dl)
--> 166         for o in enumerate(self.dl): self.one_batch(*o)
    167 
    168     def _do_one_batch(self):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/data/load.py in __iter__(self)
    101         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    102             if self.device is not None: b = to_device(b, self.device)
--> 103             yield self.after_batch(b)
    104         self.after_iter()
    105         if hasattr(self, 'it'): del(self.it)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in __call__(self, o)
    196         self.fs.append(t)
    197 
--> 198     def __call__(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
    199     def __repr__(self): return f"Pipeline: {' -> '.join([f.name for f in self.fs if f.name != 'noop'])}"
    200     def __getitem__(self,i): return self.fs[i]

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in compose_tfms(x, tfms, is_enc, reverse, **kwargs)
    148     for f in tfms:
    149         if not is_enc: f = f.decode
--> 150         x = f(x, **kwargs)
    151     return x
    152 

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in __call__(self, x, **kwargs)
     71     @property
     72     def name(self): return getattr(self, '_name', _get_name(self))
---> 73     def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
     74     def decode  (self, x, **kwargs): return self._call('decodes', x, **kwargs)
     75     def __repr__(self): return f'{self.name}:\nencodes: {self.encodes}decodes: {self.decodes}'

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in _call(self, fn, x, split_idx, **kwargs)
     81     def _call(self, fn, x, split_idx=None, **kwargs):
     82         if split_idx!=self.split_idx and self.split_idx is not None: return x
---> 83         return self._do_call(getattr(self, fn), x, **kwargs)
     84 
     85     def _do_call(self, f, x, **kwargs):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in _do_call(self, f, x, **kwargs)
     88             ret = f.returns(x) if hasattr(f,'returns') else None
     89             return retain_type(f(x, **kwargs), x, ret)
---> 90         res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
     91         return retain_type(res, x)
     92 

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in <genexpr>(.0)
     88             ret = f.returns(x) if hasattr(f,'returns') else None
     89             return retain_type(f(x, **kwargs), x, ret)
---> 90         res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
     91         return retain_type(res, x)
     92 

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in _do_call(self, f, x, **kwargs)
     87             if f is None: return x
     88             ret = f.returns(x) if hasattr(f,'returns') else None
---> 89             return retain_type(f(x, **kwargs), x, ret)
     90         res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
     91         return retain_type(res, x)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/dispatch.py in __call__(self, *args, **kwargs)
    116         elif self.inst is not None: f = MethodType(f, self.inst)
    117         elif self.owner is not None: f = MethodType(f, self.owner)
--> 118         return f(*args, **kwargs)
    119 
    120     def __get__(self, inst, owner):

/media/big_ssd/doug/Documents/GitHub/tsai/tutorial_nbs/tsai/data/image.py in encodes(self, o)
    176         else:
    177             o = o.reshape(-1, seq_len)
--> 178         output = self.encoder.fit_transform(o.cpu().numpy()).reshape(bs, -1, size, size)
    179         if self.cmap and output.shape[1] == 1:
    180             output = TSImage(plt.get_cmap(self.cmap)(output)[..., :3]).squeeze(1).permute(0,3,1,2)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    697         if y is None:
    698             # fit method of arity 1 (unsupervised transformation)
--> 699             return self.fit(X, **fit_params).transform(X)
    700         else:
    701             # fit method of arity 2 (supervised transformation)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/pyts/image/mtf.py in transform(self, X)
    140         discretizer = KBinsDiscretizer(n_bins=self.n_bins,
    141                                        strategy=self.strategy)
--> 142         X_binned = discretizer.fit_transform(X)
    143 
    144         X_mtm = _markov_transition_matrix(X_binned, n_samples,

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    697         if y is None:
    698             # fit method of arity 1 (unsupervised transformation)
--> 699             return self.fit(X, **fit_params).transform(X)
    700         else:
    701             # fit method of arity 2 (supervised transformation)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/pyts/preprocessing/discretizer.py in transform(self, X)
    121         bin_edges = self._compute_bins(
    122             X, n_samples, self.n_bins, self.strategy)
--> 123         X_new = _digitize(X, bin_edges)
    124         return X_new
    125 

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/pyts/preprocessing/discretizer.py in _digitize(X, bins)
     40     n_samples, n_timestamps = X.shape
     41     if isinstance(bins, tuple):
---> 42         X_binned = _digitize_2d(X, bins, n_samples, n_timestamps)
     43     else:
     44         if bins.ndim == 1:

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    415         except errors.UnsupportedError as e:
    416             # Something unsupported is present in the user code, add help info
--> 417             error_rewrite(e, 'unsupported_error')
    418         except (errors.NotDefinedError, errors.RedefinedError,
    419                 errors.VerificationError) as e:

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    355                 raise e
    356             else:
--> 357                 raise e.with_traceback(None)
    358 
    359         argtypes = []

UnsupportedError: Failed in nopython mode pipeline (step: ensure IR is legal prior to lowering)
Tuple 'bins' length must be smaller than 1000.
Large tuples lead to the generation of a prohibitively large LLVM IR which causes excessive memory pressure and large compile times.
As an alternative, the use of a 'list' is recommended in place of a 'tuple' as lists do not suffer from this problem.

File "../../../../../../../home/doug/anaconda3/envs/tsai2/lib/python3.8/site-packages/pyts/preprocessing/discretizer.py", line 32:
@njit()
def _digitize_2d(X, bins, n_samples, n_timestamps):
^

**Comment by oguiza** [comment] 2021-02-19 10:58
Hi @williamsdoug,
Thanks again for reviewing the tutorial nbs and creating this new issue. 
I've seen this sometime, but don't quite understand where it's coming from. This function uses a function from the pyts library. I'll dig into it as soon as I can.

**Comment by williamsdoug** [comment] 2021-03-10 17:23
Retested using 0.2.16 - fails at same point - cell 32

Something new I noticed is that the sample plots displayed using dls.show_batch() appear to be the same across samples for the univariate data in cells 7-18.  The multivariate data (cells 22+) shows significant variability by sample, as expected.    Note:  It's possible that this issue may have been present in prior tsai releases, but this is the first time noticed this pattern.

**Comment by oguiza** [comment] 2021-04-03 07:26
I've modified the number of default bins (n_bins) in TSToMTF from 8 to 5 that according to `pyts` as 5 seems to be the default value there.
I've rerun the entire notebook and it's working well in Colab.

**Comment by oguiza** [comment] 2021-04-12 09:27
I'll close this issue since I've confirmed it's working as expected. Feel free to reopen it if necessary.

**Closed by oguiza** 2021-04-12 09:27 UTC
